---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.1 包含新的增強功能。 
---
= Cloud Volumes ONTAP 9.13.1 的新功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.1 包含新的增強功能。

最新版的BlueXP也會提供其他功能和增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["BlueXP版本說明"^] 以取得詳細資料。



== 9.13.1 P12 （ 2024 年 11 月 25 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P12 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P12["檢視 P12 修補程式中修正的錯誤清單"^] （需要登入 NetApp 支援網站）。



== 9.13.1 P11 （ 2024 年 10 月 14 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P11 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P11["檢視 P11 修補程式中修正的錯誤清單"^] （需要登入 NetApp 支援網站）。



== 9.13.1 P10 （ 2024 年 8 月 8 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P10 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P10["檢視 P10 修補程式中修正的錯誤清單"^] （需要登入 NetApp 支援網站）。



== 9.13.1 第 9 頁（ 2024 年 5 月 22 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P9 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P9["檢視 P9 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 第 8 頁（ 2024 年 4 月 18 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P8 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P8["檢視 P8 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 第 7 頁（ 2024 年 4 月 1 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 9.13.1 P7 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P7["檢視 P7 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 P6 （ 2024 年 2 月 5 日）

所有雲端供應商現在都可以使用 Cloud Volumes ONTAP 的 9.13.1 P6 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P6["檢視在p6修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 P4 （ 2023 年 12 月 8 日）

所有雲端供應商現在均可使用 Cloud Volumes ONTAP 9.13.1 P4 修補程式。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P4["檢視 P4 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 P2 和 9.13.1 P3 （ 2023 年 10 月 20 日）

如果您有執行 3.9.26 版或更新版本的 Connector 、則所有雲端供應商都可以使用 9.13.1 P2 和 9.13.1 P3 修補程式 Cloud Volumes ONTAP 。BlueXP會提示您將現有系統升級至此修補程式版本。

* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P3["檢視 P3 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。
* link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P2["檢視 P2 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。




== 9.13.1 P1 （ 2023 年 10 月 3 日）

如果您有執行 3.9.26 版或更新版本的 Connector 、則所有雲端供應商都可以使用 9.13.1 P1 修補程式 Cloud Volumes ONTAP 。BlueXP會提示您將現有系統升級至此修補程式版本。

link:https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.13.1P1["檢視 P1 修補程式中修正的錯誤清單"^] （需登入 NetApp 支援網站）。



== 9.13.1 GA （ 2023 年 7 月 26 日）

Cloud Volumes ONTAP 9.13.1 的一般可用度版本現已在 AWS 、 Azure 和 Google Cloud 中推出。



== 9.13.1 RC1 （ 2023 年 6 月 26 日）

Cloud Volumes ONTAP 9.13.1 的 Release Candidate 1 現已在 AWS 、 Azure 和 Google Cloud 中推出。

FabricPool 效能的一些改善可能會影響 Cloud Volumes ONTAP 中的階層式資料。

.連續讀取速度和分層改善
由於 FabricPool 中的讀取效能和分層處理量有所改善，因此內部部署物件存放區的傳輸率和 `PUT`作業速度可能會較高 `GET`。確保有足夠的效能預留空間，提供無縫的效能。

若要深入瞭解，請參閱 https://www.netapp.com/media/17239-tr-4598.pdf["FabricPool 最佳實務做法指南"^]

.積極的預先讀取功能
 `Aggressive Readahead`FabricPool 的功能可能會增加檔案層級的讀取作業，進而增加公有雲的讀取成本和記憶體使用率。

如需詳細資訊，請參閱 ONTAP 文件： https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-aggressive-read-ahead-task.html#enable-aggressive-read-ahead-mode-during-volume-creation["啟用和停用主動式預先讀取模式"^]

.雲端寫入功能
此功能可讓 NFS 用戶端直接寫入 FabricPool 中的容量層。此功能有一定限制，使用時請務必謹慎。例如，如果將雲端寫入 NFS 流量新增至一般 ONTAP 流量（例如 SnapMirror ）， SnapMirror 中的整體恢復點目標（ RPO ）和恢復時間目標（ RTO ）可能會受到影響。

如需詳細資訊，請參閱 ONTAP 文件： https://docs.netapp.com/us-en/ontap/fabricpool/enable-disable-volume-cloud-write-task.html["啟用和停用磁碟區、以直接寫入雲端"^]



== 升級附註

請閱讀這些附註、深入瞭解升級至此版本的相關資訊。



=== 如何升級

必須從BlueXP完成升級。Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。

link:http://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-updating-ontap-cloud.html["瞭解如何在BlueXP通知您時進行升級"^]。



=== 支援的升級途徑

您可以從 9.12.1 版和 9.13.0 版升級至 Cloud Volumes ONTAP 9.13.1 版。BlueXP會提示您將合格Cloud Volumes ONTAP 的更新版升級至此版本。



=== 所需版本的Connector

BlueXP Connector 必須執行 3.9.26 版或更新版本、才能部署新的 Cloud Volumes ONTAP 9.13.1 系統、並將現有系統升級至 9.13.1 版。


TIP: 連接器的自動升級預設為啟用、因此您應該執行最新版本。



=== 停機

* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。




=== 不再支援c4、m4和r4執行個體

在AWS中Cloud Volumes ONTAP 、不再支援C4、M4和R4 EC2執行個體類型。如果現有的系統執行於c4、m4或r4執行個體類型、則必須變更為c5、m5或R5執行個體系列中的執行個體類型。您必須變更執行個體類型、才能升級至此版本。

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["瞭解如何變更EC2執行個體類型Cloud Volumes ONTAP 以供使用"^]。

請參閱 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp支援"^] 以深入瞭解這些執行個體類型的終止可用度和支援。
